stages:
  - build
  - container-build
  - release
build:
  stage: build
  image: node:6.11
  script:
    - export http_proxy='http://wwwproxy.sandia.gov:80'
    - export https_proxy='http://wwwproxy.sandia.gov:80'
    - npm install && npm run build
  artifacts:
    paths:
      - build/
release:
  stage: release
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  only:
     - develop
     - master
